// <auto-generated />
namespace RaidExec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Declined_for_RaidInvite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Declined_for_RaidInvite));
        
        string IMigrationMetadata.Id
        {
            get { return "201704052005521_added_Declined_for_RaidInvite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
